name: Funções GitHub Actions
on:
  push:
jobs:
  only-main:
    if: ${{ github.ref == 'refs/heads/hotfix' }}
    name: This job only execute on branch main
    runs-on: ubuntu-latest
    steps:
      - name: Executing on main
        run: echo "Executing command on main"