name: Matrix Github Actions
on:
  workflow_dispatch:
    inputs:
      version1:
        required: true
        type: number
      version2:
        required: true
        type: number
jobs:
  node-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04]
        node-version: ['${{ inputs.version1 }}', '${{ inputs.version2 }}']
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v
      - run: cat /etc/os-release
      - run: echo "Versão do Ubuntu é ${{ matrix.os }}"