name: Workflow CI/CD
on:
  workflow_dispatch:
    inputs:
      ambiente:
        type: string
        default: dev
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Iniciando CI
        run: echo "Iniciando CI"
  CD:
    needs: [CI]
    uses: ./.github/workflows/deploy.yml
    with:
      env: ${{ inputs.ambiente }}