name: Repository Dispatch
on:
  workflow_call:
    inputs:
      ambiente:
        type: string
        required: true
  repository_dispatch:
    types:
      - deploy-remoto
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Executando ambiente ${{ inputs.ambiente || github.event.client_payload.ambiente }}"